name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt

      - name: Setup SBT
        uses: sbt/setup-sbt@v1

      - name: Check Format
        run: sbt scalafmtCheckAll

      - name: Compile
        run: sbt compile

      - name: Test
        run: sbt test